name: Deploy Portfolio to cPanel

on:
  push:
    branches: ["master"] # Aseg칰rate que tu rama se llame 'main' o 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Descarga tu c칩digo
      - name: 游뚴 Checkout Code
        uses: actions/checkout@v4

      # 2. Instala Node.js
      - name: 游릭 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # 3. Instala dependencias y construye
      - name: 游닍 Install & Build
        env:
          # Copia esto tal cual, GitHub sustituir치 las variables autom치ticamente
          NEXT_PUBLIC_FIREBASE_API_KEY: ${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_FIREBASE_APP_ID: ${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}
        run: |
          npm install
          npm run build
          
      # 4. Sube los archivos al cPanel
      - name: 游 Upload via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Esta es la carpeta que crea Next.js con el export
          local-dir: ./out/
          # IMPORTANTE: Cambia esto si tu carpeta en cPanel tiene otro nombre.
          # Usualmente cPanel crea una carpeta con el mismo nombre del subdominio.
          server-dir: ./public_html/fpereiradev.sppa.cl/
          protocol: ftps
          exclude: |
            **/.git*
            **/.git*/**
